name: CephiniaCore
version: 1.013
description: The Core of CephiniaRPG
main: org.cephinia.core.Main
author: CephiniaTeam
commands:
  heal:
    description: Use the command to heal yourself!
    usage: /<command>
